#pragma once

#include "types.hpp"
#include "order.hpp"
#include "events.hpp"
#include <string>
#include <variant>
#include <nlohmann/json.hpp>

namespace lob {

// Request message types

struct NewOrderRequest {
    OrderId order_id = INVALID_ORDER_ID;
    TraderId trader_id = INVALID_TRADER_ID;
    std::string symbol;
    Side side = Side::BUY;
    OrderType order_type = OrderType::LIMIT;
    Price price = INVALID_PRICE;
    Quantity quantity = INVALID_QUANTITY;
    TimeInForce time_in_force = TimeInForce::DAY;
    Timestamp timestamp = 0;
    
    // Convert to Order
    Order to_order() const {
        Order order;
        order.order_id = order_id;
        order.trader_id = trader_id;
        order.symbol = symbol;
        order.side = side;
        order.order_type = order_type;
        order.price = price;
        order.quantity = quantity;
        order.remaining_quantity = quantity;
        order.time_in_force = time_in_force;
        order.timestamp = timestamp;
        return order;
    }
    
    // JSON serialization
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(NewOrderRequest, order_id, trader_id, symbol, 
                                    side, order_type, price, quantity, time_in_force, timestamp)
};

struct CancelRequest {
    OrderId order_id = INVALID_ORDER_ID;
    std::string symbol;
    Timestamp timestamp = 0;
    
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(CancelRequest, order_id, symbol, timestamp)
};

struct ReplaceRequest {
    OrderId order_id = INVALID_ORDER_ID;
    std::string symbol;
    Price new_price = INVALID_PRICE;
    Quantity new_quantity = INVALID_QUANTITY;
    Timestamp timestamp = 0;
    
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(ReplaceRequest, order_id, symbol, new_price, 
                                    new_quantity, timestamp)
};

// Response message types

struct OrderResponse {
    ResultCode result = ResultCode::SUCCESS;
    OrderId order_id = INVALID_ORDER_ID;
    std::string message;
    
    // Events generated by this operation
    std::vector<TradeEvent> trades;
    std::vector<OrderAcceptedEvent> accepts;
    std::vector<OrderRejectedEvent> rejects;
    std::vector<OrderCancelledEvent> cancels;
    std::vector<OrderReplacedEvent> replaces;
};

} // namespace lob

